export const WORLD_INITIALIZE_START = 'WORLD_INITIALIZE_START'
export const WORLD_INITIALIZE_COMPLETE = 'WORLD_INITIALIZE_COMPLETE'

export const SET_PROGRESS = 'WORLD_PROGRESS'
export const SET_VERSION = 'WORLD_VERSION'
export const SET_READY = 'WORLD_READY'
export const SET_MODE = 'WORLD_MODE'
